version: "3"
volumes:
  dados:
networks:
  cache:
  database:
services:
  web:
    image: golang:1.8
    ports:
      - 5000:5000
    networks:
      - cache
      - database
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
    networks:
      - cache
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database
