version: "3"
volumes:
  dados:
services:
  web:
    build: ./
    ports:
      - 5000:5000
    depends_on:
      - db
      - cache
  cache:
    image: redis:3-alpine
  db:
    image: postgres:alpine
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
